language: scala
scala:
   - 2.10.0
   - 2.10.4
   - 2.11.7
jdk:
  - oraclejdk7
  - openjdk7
addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
